engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
    checks:
      Similar code:
        enabled: false
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- "Gulpfile.js"
- "karma.conf.js"
- "test.conf.js"
- "test.main.js"
- "protractor.conf.js"
- "tools/**/*"
- "src/client/assets/**/*"
- "src/client/css/style.css"
- "misc/**/*"
