language: node_js
node_js: 6

sudo: false

install: true  # yarn bug

services:
  - docker

addons:
  firefox: "45.0"

branches:
  only: master

os:
  - linux

before_install:
  - export CHROME_BIN=chromium-browser; fi  # Karma CI
  - export DISPLAY=:99.0; fi
  #Set up Docker exports
  - export AUTHOR=`git --no-pager show -s --format='%an <%ae>'`
  - export DATE=`TZ=America/New_York date "+%m-%d-%y-%H%M"`
  - export DATE_TM=`TZ=America/New_York date "+%m-%d-%y %H:%M"`  
  - export DOCKER_IMAGE="fnlcr/nci-adult-match-ui"
  - echo "{\"buildNumber\":\"build "$TRAVIS_BUILD_NUMBER"\", \"buildTime\":\""$DATE_TM"\", \"buildId\":\""$TRAVIS_BUILD_ID"\", \"docker\":\""$$DOCKER_IMAGE:$DATE"\"}" > src/client/assets/build-info.json
  - cat ./src/client/assets/build-info.json

before_script:
  - npm install
  - sh -e /etc/init.d/xvfb start; fi
  - nohup bash -c "webdriver-manager start 2>&1 &"; fi  # Protractor CI

script:
  - npm run build.inttest
  # - npm run build.inttest && npm test
  - docker build -f .docker/dockerfile.httpd -t $DOCKER_IMAGE:$DATE -t $DOCKER_IMAGE:latest .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

after_failure:
  - cat /home/travis/build/nci-adult-match-ui/npm-debug.log

after_success:
  - cat coverage_js/lcov.info | ./node_modules/.bin/codacy-coverage -t $CODACY_PROJECT_TOKEN -d -v
  - docker images
  - docker push $DOCKER_IMAGE # Pushes both date and latest
  ##Deploy to AWS IntTest
  - docker run -it --rm -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY 
    -e AWS_DEFAULT_REGION=us-east-1 silintl/ecs-deploy 
    --cluster AdultMatch-IntTest-Backend --service-name AdultMATCH-nci-adult-match-ui-INTTEST 
    -i $DOCKER_IMAGE:$DATE
  ##Trigger Travis bdd tests
  # - curl -s -X POST -H "Content-Type:application/json" -H "Accept:application/json" 
  #   -H "Travis-API-Version:3" -H "Authorization:token $TRAVIS_TOKEN" 
  #   -d "{\"request\":{\"message\":\"Triggered by nci-adult-match-ui $TRAVIS_COMMIT\", \"branch\":\"master\", \"config\":{\"env\":{\"matrix\":[\"TRIGGER_REPO=nci-match-ui;TRIGGER_VER=$DATE;CUC_TAG=@ui;AUTHOR=$AUTHOR\"]}}}}" 
  #   https://api.travis-ci.org/repo/CBIIT%2Fnci-adult-match-bddtests/requests

notifications:
  slack: clinicalbiomed:k1HFjdqTwI4yvSyQWPulUEK4

cache:
  directories: node_modules
