version: '2'

services:

  nci-adult-match-ui:
    build:
      context: .
      dockerfile: ./.docker/nci-adult-match-ui.production.dockerfile
    command: npm run build.prod
    container_name: nci-adult-match-ui-build-prod
    image: nci-adult-match-ui
    networks:
      - prod-network
    volumes:
      - ./dist:/home/app/nci-adult-match-ui/dist

  nci-adult-match-ui-nginx:
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/nci-adult-match-ui.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    container_name: nci-adult-match-ui-nginx-prod
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    image: nginx
    networks:
      - prod-network
    ports:
      - '5555:80'
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/conf.d/nci-adult-match-ui.template
      - ./dist/prod:/var/www/dist/prod

networks:
  prod-network:
    driver: bridge
