version: '3'

services:
  ui:
    build:
      context: .
      dockerfile: ./.docker/dockerfile.development
    command: npm start
    container_name: nci-adult-match-ui-dev
    image: nci-adult-match-ui
    networks:
      - dev-network
    ports:
      - '5555:5555'

networks:
  dev-network:
    driver: bridge
