version: "3"
services:
  ui:
    build:
      context: .
      dockerfile: ./.docker/dockerfile.node
    command: npm run start.dev-docker
    image: "fnlcr/nci-adult-match-ui-dev"
    ports:
      - '5555:5555'
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
  patient-api:
    image: "fnlcr/nci-adult-match-patient-api"
    command: python app.py
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
  mongo:
    image: mongo:3.4.0
    volumes:
      - ./misc/data_setup/match:/backup
    ports:
      - "27017:27017"
volumes: 
  node_modules:
