version: '2'

services:

  nci-adult-match-ui:
    build:
      context: .
      dockerfile: ./.docker/nci-adult-match-ui.development.dockerfile
    command: npm start
    container_name: nci-adult-match-ui-start
    image: nci-adult-match-ui
    networks:
      - dev-network
    ports:
      - '5555:5555'

networks:
  dev-network:
    driver: bridge
