version: '2'

services:

  nci-match-ui-adult-study:
    build:
      context: .
      dockerfile: ./.docker/nci-match-ui-adult-study.production.dockerfile
    command: npm run build.prod
    container_name: nci-match-ui-adult-study-build-prod
    image: nci-match-ui-adult-study
    networks:
      - prod-network
    volumes:
      - ./dist:/home/app/nci-match-ui-adult-study/dist

  nci-match-ui-adult-study-nginx:
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/nci-match-ui-adult-study.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    container_name: nci-match-ui-adult-study-nginx-prod
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    image: nginx
    networks:
      - prod-network
    ports:
      - '5555:80'
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/conf.d/nci-match-ui-adult-study.template
      - ./dist/prod:/var/www/dist/prod

networks:
  prod-network:
    driver: bridge
