version: "3"
services:
  ui:
    build:
      context: .
      dockerfile: ./.docker/dockerfile.development
    command: npm start
    container_name: nci-adult-match-ui
    image: "match/nci-adult-match-ui:latest"
    ports:
      - '5555:5555'
  patient-api:
    image: "match/nci-adult-match-patient-api"
    command: python app.py
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    image: mongo:3.4.0
    volumes:
      - ./data_setup/match:/backup
    ports:
      - "27017:27017"
