version: "3"
services:
  ui:
    build:
      context: .
      dockerfile: ./.docker/dockerfile.httpd
    command: httpd-foreground -C 'DocumentRoot /usr/local/apache2/match/'
    image: "matchbox/nci-adult-match-ui:latest"
    ports:
      - '5555:80'
  patient-api:
    image: "matchbox/nci-adult-match-patient-api"
    command: python app.py
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    image: mongo:3.4.0
    volumes:
      - ./misc/data_setup/match:/backup
    ports:
      - "27017:27017"
