development:
  port: 5000
  visibility_timeout: '36000'
  region: "us-east-1"
  bucket: "adultmatch-dev"
  aws_download_time_limit: 600
  tmp_file_dir: "/tmp"
  treatment_arm_api_url: "http://treatment-arm-api:5010/api/v1/treatment_arms"
  assay_activation_rules_file: "config/assay_activation_rules.json"
  logger_level: "WARN"
