APEC1621SC:
  development:
    match_ui_endpoint: 'http://localhost:9000'
    dynamo_endpoint: "http://dynamo:8000"
    patient_endpoint: "http://localhost:10240"
    rule_endpoint: "http://localhost:10250"
    patient_post_path: "/api/v1/patients/variant_report/"
    rule_path: "/api/v1/rules/sample_control_report/"
    events_path: "/api/v1/patients/events"
    shipments_path: "/api/v1/patients/shipments/"
    shipment_status: "/api/v1/patients/shipment_status/"
    auth0_url: "https://ncimatch.auth0.com"
    auth0_username: "ped-matchbox-dev@mail.nih.gov"
    bot_name: "PED_MATCHBOTDEV"
    slack_channel_id: "C2NE9M08N"
    icon_emoji: ":face_with_head_bandage:"
    requeue_countdown: 10800
    visibility_timeout: '36000'
    region: "us-east-1"
    port: "10241"
    bucket: "pedmatch-dev"
    db_files_bucket: "match-uploader-dev"
    tmp_file_dir: "/tmp"
    polling_interval: 10
    read_capacity: 5
    write_capacity: 5
    aws_download_time_limit: 600
    aws_upload_time_limit: 3600
    ir_queue_name: pedmatch-dev_ion_reporter_queue3
    mailer_from: "ped-matchbox-int@mail.nih.gov"
    smtp_settings_address: "email-smtp.us-east-1.amazonaws.com"
    smtp_settings_port: "587"

EAY131:
  development:
    match_ui_endpoint: 'http://localhost:9000'
    dynamo_endpoint: "http://dynamo:8000"
    patient_endpoint: "http://localhost:10240"
    rule_endpoint: "http://localhost:10250"
    patient_post_path: "/api/v1/patients/variant_report/"
    rule_path: "/api/v1/rules/sample_control_report/"
    events_path: "/api/v1/patients/events"
    shipments_path: "/api/v1/patients/shipments/"
    shipment_status: "/api/v1/patients/shipment_status/"
    auth0_url: "https://ncimatch.auth0.com"
    auth0_username: "ped-matchbox-dev@mail.nih.gov"
    bot_name: "ADULT_MATCHBOTDEV"
    slack_channel_id: "C2NE9M08N"
    icon_emoji: ":face_with_head_bandage:"
    requeue_countdown: 10800
    visibility_timeout: '36000'
    region: "us-east-1"
    port: "10241"
    db_files_bucket: "match-uploader-dev"
    tmp_file_dir: "/tmp"
    polling_interval: 10
    read_capacity: 5
    write_capacity: 5
    aws_download_time_limit: 600
    aws_upload_time_limit: 3600
    bucket: adultmatch-dev
    ir_queue_name: adultmatch-dev_ion_reporter_queue3
    mailer_from: "matchbox-int@mail.nih.gov"
    smtp_settings_address: "email-smtp.us-east-1.amazonaws.com"
    smtp_settings_port: "587"
