FROM node:6

ENV HOME=/usr/src/app
RUN mkdir $HOME
WORKDIR $HOME

COPY . .

RUN npm install -g gulp \
    && npm install \
    && npm rebuild node-sass

EXPOSE 5555

CMD ["npm", "run", "start.dev-docker"]
