FROM node:6

ENV HOME=/usr/src/app
RUN mkdir $HOME
WORKDIR $HOME

COPY . .

RUN npm install -g gulp \
    && npm install \
    && ./node_modules/.bin/gulp build.bundle.rxjs \
    && npm run build.dev-docker

EXPOSE 5555

CMD npm run serve.dev-docker
