# Base image 
FROM httpd:2.4
MAINTAINER jeremy.pumphrey@nih.gov

RUN apt-get update && apt-get install -y && rm -rf /var/lib/apt/lists/*

ENV HOME=/usr/local/apache2
WORKDIR $HOME

ENV APP_NAME=nci-adult-match-ui

RUN mkdir $HOME/$APP_NAME/

COPY ./dist/prod $HOME/$APP_NAME/

CMD httpd-foreground -C 'DocumentRoot $HOME/$APP_NAME/'
